# -*- coding: utf-8 -*-
"""K-Means.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XZgcyQwSnBWD6h121MU1vehxQk0qHE2n
"""

from sklearn.cluster import KMeans
import pandas as pd
from sklearn.metrics import davies_bouldin_score

path = '/content/drive/MyDrive/Dataset/Sederhana/iris.csv'
dataset = pd.read_csv(path)

atribut = ["sepal length","sepal width","petal length","petal width"]
data = dataset.loc[:, atribut]

kmeans = KMeans(n_clusters = 3)
kmeans = kmeans.fit(data)

label = kmeans.labels_

kmeans.cluster_centers_

kmeans.predict([[0, 0, 1, 1]])

davies_bouldin_score(data, label)